// js/ocrKeywords.js
const OCR_KEYWORDS = {
  mobile: [
    "Mob", "mobile",
    "Cell",
    "Handy",
    "M:", "M.", "M +",
    "行動", "手機", "機:", "手提",
    "+",
  ],
  phone: [
    "Tel","Tel:",
    "Phone","Phone direct", "Direct",
    "Ph",
    "Office",
    "T:", "T.",
    "D:",
    "電話",
    "話:",
    "代表",
    "+",
    "(",
    "0",
    ")",
  ],
address:  [
  // 中文地址關鍵字
  "路", "號", "樓", "室",
  "區", "縣", "市", "省", "鄉", "鎮", "村", "里", "巷", "弄", "段",
   
  // English address keywords
  "Avenue",
  "Boulevard",
  "City",
  "Country",
  "Street", "St.",
  "Road", "Rd.",
  "St.",
  "Ln", "Ln.",
  /*"Aly.",*/
  "RUE",
  "Ave", "Ave.",
  "Blvd", "Blvd.",
  "Ct.",
  "Pl.",
  "Dist.", "Dist",
  "No.",
  "Suite",
  "Ste.",
  "Floor", "Fl.",
  "Building", "Bldg.",
  "Park",
  "Tower",
  "Center", "Centre",
  
  // 
  "Taiwan", "R.O.C.", "Republic of China",
  "USA", "United States",
  "Japan", "日本",
  "China",
  "Germany",
  "France", "Netherlands", "Belgium",
  "South Korea", "Korea",
  "UK", "U.K.", "United Kingdom",

  // 郵遞區號符號
  "〒",

  // USA states abbreviations
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",  
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
  "Washington D.C.",
  "Puerto Rico",
  "Virgin Islands",
  "Guam",
  "American Samoa",
],
  fax: ["Fax", "F:", "F.", "傳真", "真:"],
  email: ["@", "Email", "E-mail", "E:", "E.", "郵箱", "信箱", "電子郵件"],
  website: [
    "http",
    "www.",
    ".com",
    ".tw",
    ".cn",
    ".ch",
    ".jp",
    ".de",
    ".nl",
    ".fr",
    ".kr",
    ".net",
    "Web",
    "Website",
    "網址",
    "網頁",
    ".org",
    ".io",
    ".biz",
    ".co",
    ".info",
  ],
  taxId: ["統一編號", "統編", "Tax ID", "VAT", "GUI", "TAX", "TAX No"],
  company: [
    "DELL", "IBM", "Google", "aws", "AWS", "Oracle", "Amazon", "Meta",
    "Micron", "Intel", "Microsoft", "Apple", "Samsung", "Hynix", "Sandisk",
    "Co.",
    "Ltd",
    "Inc",
    "Corp",
    "GmbH",
    "AG",
    "Group",
    "Company",
    "Limited",
    "Technology", "Tech",
    "University", "Universität",
    "College",
    "School",
    "公司",
    "集團",
    "株式會社","株式会社","製作所",
    "有限公司",
    "股份",
    "工作室",
    "企業",
    "商行",
    "大學", "學院",
    "LLC",
    "Enterprise","AG",
    "®"
  ],
  dept: [
    "Department", "Dept",
    "Div",
    "Division",
    "Team", "메모리사업부", "상품기획팀",
    "Center",
    "BU",
    "Unit",
    "Service", "Services",
    "Management",
    "Operations",
    "Section",
    "處",
    "中心","セ ン タ",
    "部門", "部",
    "課",
    "事業",
  ],
  job: [
    "Manager", "Mgr",
    "Director",
    "Chief",
    "Engineer",
    "Specialist",
    "Senior",
    "Assistant",
    "President",
    "Founder",
    "CEO","Geschäftsführer",
    "CTO",
    "CFO",
    "COO",
    "Fellow",
    "representative",
    "Head",
    "VP",
    "Sr", "Sr.", 
    "Jr", "Jr.",
    "Lead", "リーダー",
    "Supervisor",
    "Staff",
    "PhD",
    "MD",
    "Dr.",
    "Prof.",
    "Ph.D.", "Dipl.",
    "Architect",
    "Sales",
    "CFA",
    "經理",
    "副理",
    "總監",
    "主任",
    "專員",
    "業務",
    "資深",
    "工程師",
    "處長",
    "執行長",
    "營運長",
    "董事",
    "董事長",
    "特助",
    "顧問",
    "代表",
    "負責人",
    "取締役", "監査役", "社長", "役員", "部長",
    "課長", "室長", "組長",
    "專家",
    "領班",
    "主管",
    "助理",
    "博士", "教授",
    "이사",
  ],
  industry: [
    "科技", "資訊", "實業",
    "工業", "貿易", "國際",
    "電子", "生技", "文化",
    "創意", "設計", "物流",
    "System", 
    "Digital",
    "Consulting",
    "Solutions", "シ ス テ ム ソ リ ュ ー シ", "ン プ ロ ジ ェ ク ト",
    "Industry",
    "International", 
  ],
};